# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
bom = "5.0.0"

kotlin = "2.3.0"
spotless = "8.1.0"
junit = "6.0.1"

ksp = "2.3.4"
kotlinpoet = "2.2.0"
dagger = "2.58"

[libraries]
bom = { module = "com.gitee.ixtf:bom", version.ref = "bom" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
